// Generated by CoffeeScript 1.4.0
(function() {
  var mintpressoAPIKey, _soran;

  mintpressoAPIKey = '48d54bf7e4fa5e7abb6a2f4ecf8b096e::1';

  _soran = {
    user: {
      name: '',
      mintpresso: ''
    },
    addUser: function(info) {
      var data;
      if (info.name.length !== 0 && this.user.name !== info.name) {
        this.user.name = info.name;
        data = {
          type: 'user',
          identifier: "bugs-" + this.user.name
        };
        return mintpresso.set(data);
      }
    },
    addMusic: function(info, callback) {
      var data;
      data = {
        type: "music",
        identifier: "" + info.serviceName + "-" + info.id,
        data: {
          albumArtist: info.albumArtist,
          albumTitle: info.albumTitle,
          artist: info.artist,
          genre: info.genre,
          length: info.length,
          releaseDate: info.releaseDate,
          title: info.title
        }
      };
      return mintpresso.set(data);
    },
    listenMusic: function(music) {
      return true;
    }
  };

  chrome.extension.onConnect.addListener(function(port) {
    var tab;
    window["mintpresso"].init(mintpressoAPIKey, {
      withoutCallback: true
    });
    tab = port.sender.tab;
    return port.onMessage.addListener(function(info) {
      switch (info.kind) {
        case 'bugsUserName':
          return _soran.addUser(info);
        case 'bugsTrack':
          return _soran.addMusic(info, function(m) {
            return _soran.listenMusic(m);
          });
      }
    });
  });

}).call(this);
