// Generated by CoffeeScript 1.4.0
(function() {

  chrome.extension.onConnect.addListener(function(port) {
    var tab;
    tab = port.sender.tab;
    return port.onMessage.addListener(function(info) {
      return console.log(info);
    });
  });

}).call(this);
