// Generated by CoffeeScript 1.4.0
(function() {
  var __soran;

  __soran = {
    init: function(conn) {
      var data;
      this.conn = conn;
      data = {
        kind: 'bugsUserName',
        name: $('.username').find('strong').text()
      };
      this.conn.postMessage(data);
      return this;
    },
    getBugsTrackInfo: function(trackNum, callback) {
      var options, that;
      that = this;
      options = {
        url: "http://music.bugs.co.kr/player/track/" + trackNum,
        success: function(data) {
          return callback(that.track(data.track.artist_nm, data.track.album_artist_nm, data.track.album_title, data.track.track_title, data.track.genre_dtl, data.track.len, data.track.release_ymd));
        },
        error: function(jqXHR, textStatus, errorThrow) {
          return callback(void 0);
        }
      };
      return $.ajax(options);
    },
    track: function(artist, albumArtist, albumTitle, title, genre, length, releaseDate) {
      var data;
      data = {
        artist: artist,
        albumArtist: albumArtist,
        albumTitle: albumTitle,
        title: title,
        genre: genre,
        length: length,
        releaseDate: releaseDate
      };
      return data;
    }
  };

  __soran.init(chrome.extension.connect());

  $('li.listRow').on('click', function(e) {
    var trackNumber;
    trackNumber = $(this).find('input[name=_isStream]').attr('value');
    __soran.getBugsTrackInfo(trackNumber, function(track) {
      track.serviceName = 'bugs';
      track.id = trackNumber;
      track.kind = 'bugsTrack';
      __soran.chromeConn.postMessage(track);
      return __soran.conn.postMessage;
    });
    return true;
  });

}).call(this);
